//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Entitty
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DETAIL
    {
        public int ItemId { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> PriceOrder { get; set; }
    
        public virtual ITEM ITEM { get; set; }
        public virtual ORDER ORDER { get; set; }
    }
}
